(in-package #:nyaa/tests)
(in-suite :nyaa)

;;; The UI contract (~takeiteasy/nyaa#193, #194): :RUN-START and :STEER, the
;;; :AGENT and :PARENT tags, and :SUBSCRIBE / :UNSUBSCRIBE.

(defun run-dones (recorder)
  (bt:with-lock-held ((recorder-lock recorder))
    (count :run-done (recorder-events recorder) :key (lambda (e) (getf e :type)))))

(defun await-run-dones (recorder n)
  (is-true (eventually (lambda () (>= (run-dones recorder) n)) 5)))

(defun mount-assistant (&rest initargs)
  (apply #'m:mount *ctx* 'nyaa:agent :name :assistant :model :provider-test-keyed initargs))

(defun send-to-assistant (message)
  "MESSAGE to :ASSISTANT's live process, retried while mount is still
restarting it after its last run. Returns the answer."
  (let (answer)
    (is-true (eventually (lambda ()
                           (multiple-value-bind (value status)
                               (ignore-errors (m:call (m:lookup :assistant) message))
                             (when (null status)
                               (setf answer value)
                               t)))
                         5))
    answer))

(defun run-assistant (recorder n &optional (text "hi"))
  (send-to-assistant (list :run :messages (list (list :role :user :content text))))
  (await-run-dones recorder n))

(defun types-of (events) (event-types events))

(test a-run-opens-with-run-start-and-every-event-is-tagged
  (with-agent ((streamed-reply "ok"))
    (let* ((recorder (make-recorder))
           (messages '((:role :user :content "hi")))
           (result (agent-turn :messages messages :sink (recorder-sink recorder)))
           (events (recorded-events recorder)))
      (is (eq :ok (first result)))
      (is (equal '(:run-start :turn :text-delta :done :run-done) (types-of events)))
      (is (equal messages (getf (first events) :messages)))
      (is (null (getf (first events) :continue)))
      (dolist (event events)
        (is (member :agent event) "~s carries :agent" (getf event :type))
        (is (not (member :parent event)) "~s is the root's" (getf event :type))))))

(test a-named-agent-reports-its-name-on-every-event
  (with-agent ((streamed-reply "ok"))
    (let ((recorder (make-recorder)))
      (mount-assistant :sink (recorder-sink recorder))
      (run-assistant recorder 1)
      (dolist (event (recorded-events recorder))
        (is (eq :assistant (getf event :agent)) "~s" (getf event :type))))))

(test a-steer-before-a-run-is-announced-as-it-folds-in
  (with-agent ((streamed-reply "ok"))
    (let ((recorder (make-recorder)))
      (mount-assistant :sink (recorder-sink recorder))
      (send-to-assistant '(:steer :content "first"))
      (run-assistant recorder 1)
      (let* ((events (recorded-events recorder))
             (steer (find :steer events :key (lambda (e) (getf e :type)))))
        (is (equal '(:run-start :steer :turn) (subseq (types-of events) 0 3)))
        (is (equal "first" (getf steer :content)))
        (is (null (getf steer :interrupt)))
        (is (member :input-id steer))))))

(test a-continued-run-says-so
  (with-agent ((streamed-reply "ok"))
    (let ((recorder (make-recorder)))
      (mount-assistant :sink (recorder-sink recorder))
      (run-assistant recorder 1)
      (send-to-assistant '(:run :continue t :messages ((:role :user :content "again"))))
      (await-run-dones recorder 2)
      (let ((starts (remove :run-start (recorded-events recorder)
                            :key (lambda (e) (getf e :type)) :test-not #'eq)))
        (is (equal '(nil t) (mapcar (lambda (e) (getf e :continue)) starts)))))))

(test two-subscribers-each-see-every-run-in-order
  (with-agent ((streamed-reply "ok"))
    (let* ((one (make-recorder))
           (two (make-recorder))
           (sink-one (recorder-sink one))
           (sink-two (recorder-sink two)))
      (mount-assistant)
      (is (equal '(:ok (:running nil)) (send-to-assistant (list :subscribe sink-one))))
      (send-to-assistant (list :subscribe sink-two))
      (send-to-assistant (list :subscribe sink-two))
      (run-assistant one 1)
      (await-run-dones two 1)
      (run-assistant one 2)
      (await-run-dones two 2)
      (dolist (recorder (list one two))
        (is (equal '(:run-start :turn :text-delta :done :run-done
                     :run-start :turn :text-delta :done :run-done)
                   (types-of (recorded-events recorder))))
        (is (not (recorder-overlapped recorder)))))))

(test an-unsubscribed-sink-hears-nothing-more
  (with-agent ((streamed-reply "ok"))
    (let* ((one (make-recorder))
           (two (make-recorder))
           (sink-one (recorder-sink one))
           (sink-two (recorder-sink two)))
      (mount-assistant)
      (send-to-assistant (list :subscribe sink-one))
      (send-to-assistant (list :subscribe sink-two))
      (run-assistant one 1)
      (await-run-dones two 1)
      (is (eq :ok (send-to-assistant (list :unsubscribe sink-two))))
      (run-assistant one 2)
      (is (= 1 (run-dones two)))
      (is (= 10 (length (recorded-events one))))
      (is (= 5 (length (recorded-events two)))))))

(test the-mount-sink-cannot-be-unsubscribed-and-bad-sinks-are-refused
  (with-agent ((streamed-reply "ok"))
    (let* ((recorder (make-recorder))
           (sink (recorder-sink recorder)))
      (mount-assistant :sink sink)
      (is (nyaa:tool-error-p (send-to-assistant (list :unsubscribe sink))))
      (is (nyaa:tool-error-p (send-to-assistant (list :unsubscribe (lambda (e) e)))))
      (is (nyaa:tool-error-p (send-to-assistant '(:subscribe 42))))
      (is (nyaa:tool-error-p (send-to-assistant '(:subscribe nil))))
      (send-to-assistant (list :subscribe sink))
      (run-assistant recorder 1)
      (is (= 5 (length (recorded-events recorder))) "the mount sink is not told twice"))))

(test a-subscriber-joining-mid-run-hears-the-rest-of-it
  (let ((release (list nil))
        (early (make-recorder))
        (late (make-recorder)))
    (with-agent ((interruptible-backend release))
      (unwind-protect
           (progn
             (mount-assistant)
             (send-to-assistant (list :subscribe (recorder-sink early)))
             (send-to-assistant '(:run :messages ((:role :user :content "go"))))
             (is-true (eventually (lambda () (recorder-has early :text-delta))))
             (is (equal '(:ok (:running t :turn 1))
                        (send-to-assistant (list :subscribe (recorder-sink late)))))
             (setf (car release) t)
             (await-run-dones late 1)
             (let ((types (types-of (recorded-events late))))
               (is (not (member :run-start types)))
               (is (eq :run-done (car (last types))))))
        (setf (car release) t)))))

(test a-subscription-goes-with-an-unmounted-agent
  (with-agent ((streamed-reply "ok"))
    (let ((recorder (make-recorder)))
      (mount-assistant)
      (send-to-assistant (list :subscribe (recorder-sink recorder)))
      (run-assistant recorder 1)
      (m:unmount *ctx* :assistant)
      (let ((fresh (make-recorder)))
        (mount-assistant :sink (recorder-sink fresh))
        (run-assistant fresh 1)
        (recorded-events fresh)
        (is (eql 1 (run-dones recorder)))))))

(test a-subscription-goes-with-an-agent-that-is-killed-and-not-restarted
  (with-agent ((streamed-reply "ok"))
    (let ((recorder (make-recorder)))
      (mount-assistant :restart :temporary)
      (send-to-assistant (list :subscribe (recorder-sink recorder)))
      (run-assistant recorder 1)
      (m:kill (m:lookup :assistant))
      (is-true (eventually (lambda () (null (m:lookup :assistant)))))
      (let ((fresh (make-recorder)))
        (mount-assistant :sink (recorder-sink fresh))
        (run-assistant fresh 1)
        (recorded-events fresh)
        (is (eql 1 (run-dones recorder)))))))

(test a-mounted-agent-stays-up-and-keeps-its-conversation-after-a-run
  (with-agent ((streamed-reply "ok"))
    (let ((recorder (make-recorder)))
      (mount-assistant :sink (recorder-sink recorder))
      (let ((process (m:lookup :assistant)))
        (run-assistant recorder 1 "first")
        (send-to-assistant '(:run :continue t :messages ((:role :user :content "second"))))
        (await-run-dones recorder 2)
        (is (eq process (m:lookup :assistant)))
        (let ((body (getf (car (last (requests))) :body)))
          (is (search "first" body))
          (is (search "second" body)))
        (let ((messages (getf (m:call process '(:snapshot)) :messages)))
          (is (equal '(:user :assistant :user :assistant)
                     (mapcar (lambda (m) (getf m :role)) messages))))))))

(test a-run-without-continue-starts-a-fresh-conversation-on-a-mounted-agent
  (with-agent ((streamed-reply "ok"))
    (let ((recorder (make-recorder)))
      (mount-assistant :sink (recorder-sink recorder))
      (run-assistant recorder 1 "first")
      (run-assistant recorder 2 "second")
      (is (not (search "first" (getf (car (last (requests))) :body)))))))

(test a-stale-step-or-deadline-does-not-touch-an-idle-or-later-run
  (with-agent ((streamed-reply "ok"))
    (let ((recorder (make-recorder)))
      (mount-assistant :sink (recorder-sink recorder))
      (run-assistant recorder 1)
      (let ((before (length (requests)))
            (process (m:lookup :assistant)))
        (m:cast process '(:step 1))
        (m:cast process '(:deadline 1))
        (m:call process '(:describe))
        (sleep 0.2)
        (is (= before (length (requests))) "a stale :step asks the model for nothing")
        (run-assistant recorder 2)
        (m:cast process '(:deadline 1))
        (m:call process '(:describe))
        (is (eq :stop (getf (car (last (recorded-events recorder))) :reason)))))))

(test a-sub-agents-events-carry-parent-and-do-not-end-the-parents
  (let ((n 0))
    (with-agent ((lambda (&rest request)
                   (declare (ignore request))
                   (case (incf n)
                     (1 (sse-tool-call "c1" "agent-task" "{\"task\":\"help\"}"))
                     (2 (streamed-reply "sub-answer"))
                     (t (streamed-reply "done")))))
      (let* ((recorder (make-recorder))
             (result (agent-turn :messages '((:role :user :content "go"))
                                 :sub-agents t :sink (recorder-sink recorder)))
             (events (recorded-events recorder)))
        (is (eq :ok (first result)))
        (let ((children (remove-if-not (lambda (e) (member :parent e)) events))
              (roots (remove-if (lambda (e) (member :parent e)) events)))
          (is (equal '(:run-start :turn :text-delta :done :run-done) (types-of children)))
          (is (equal '(:run-start :turn :tool-call-delta :done :tool-call :tool-result :turn :text-delta :done :run-done)
                     (types-of roots)))
          (is (eq :run-done (getf (car (last events)) :type)))
          (is (not (member :parent (car (last events))))
              "the run is over at the :run-done with no :parent key")
          (is (< (position-if (lambda (e) (and (member :parent e) (eq :run-done (getf e :type))))
                              events)
                 (position :tool-result events :key (lambda (e) (getf e :type))))))))))

(defun stalling-sub-agent-backend (release)
  "The parent's first turn delegates a task; the child's turn streams
\"partial \" and stalls until RELEASE's car is set; later turns answer at once."
  (let ((n 0))
    (lambda (&rest request)
      (declare (ignore request))
      (case (incf n)
        (1 (sse-tool-call "c1" "agent-task" "{\"task\":\"help\"}"))
        (2 (list :stall
                 (format nil "HTTP/1.1 200 OK~c~cContent-Type: text/event-stream~c~cConnection: close~c~c~c~c~a"
                         #\Return #\Newline #\Return #\Newline #\Return #\Newline
                         #\Return #\Newline (sse-body (delta-chunk "partial ")))
                 (lambda () (not (car release)))))
        (t (streamed-reply "done"))))))

(test a-subscriber-joining-mid-run-hears-a-sub-agent-through-the-parents-fanout
  (let ((release (list nil))
        (early (make-recorder))
        (late (make-recorder)))
    (with-agent ((stalling-sub-agent-backend release))
      (unwind-protect
           (progn
             (mount-assistant :sub-agents t)
             (send-to-assistant (list :subscribe (recorder-sink early)))
             (send-to-assistant '(:run :messages ((:role :user :content "go"))))
             (is-true (eventually (lambda () (recorder-has early :text-delta))))
             (send-to-assistant (list :subscribe (recorder-sink late)))
             (setf (car release) t)
             (await-run-dones late 2)
             (let* ((events (recorded-events late))
                    (child-done (position-if (lambda (e) (and (member :parent e)
                                                              (eq :run-done (getf e :type))))
                                             events)))
               (is (integerp child-done) "the child's :run-done reached the late subscriber")
               (is (find :tool-result events :key (lambda (e) (getf e :type)) :start (or child-done 0)))
               (is (not (member :parent (car (last events)))))
               (is (eq :run-done (getf (car (last events)) :type)))))
        (setf (car release) t)))))
